// <auto-generated />
using System;
using AiAnswerBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiAnswerBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AiAnswerBackend.Model.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AppDesc")
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("AppIcon")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<byte>("AppType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("varchar(512)");

                    b.Property<byte>("ReviewStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime?>("ReviewTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("ScoreStrategy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AppName");

                    b.ToTable("app");
                });

            modelBuilder.Entity("AiAnswerBackend.Model.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("question");
                });

            modelBuilder.Entity("AiAnswerBackend.Model.ScoringResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("ResultDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResultPicture")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("ResultProp")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<int>("ResultScoreRange")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("scoring_result");
                });

            modelBuilder.Entity("AiAnswerBackend.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserAccount")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UserAvatar")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("UserProfile")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("AiAnswerBackend.Model.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AppId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("AppType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Choices")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("ResultDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResultName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResultPicture")
                        .IsRequired()
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("ResultScore")
                        .HasColumnType("int");

                    b.Property<byte>("ScoreStrategy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0);

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("UserId");

                    b.HasIndex("AppId", "UserId");

                    b.ToTable("user_answer");
                });
#pragma warning restore 612, 618
        }
    }
}
